project:
  type: website
  output-dir: docs

website:
  title: "Clément Guichet"
  favicon: "lpnc.jpeg"
  open-graph: true
  twitter-card: true
  page-navigation: true
  repo-url: https://github.com/ClementGuichet/quarto_web_clem
  search: 
    type: overlay
  
  page-footer: 
    background: light
    border: false
    center: "Copyright © 2023, Clement Guichet"
    
  navbar: 
    background: light
    logo: "logo.png"
    title: false
    collapse-below: lg
    left: 
      - text: "Guide"
        menu: 
          - text: "Basic Setup"
            href: basic_setup.qmd
          - text: "DTI pipeline (SC)"
            href: DTI.qmd
          - text: "Parallel computing"
            href: parallel.qmd
          - text: "rs-fMRI pipeline (FC)"
            href: rs-fMRI.qmd
      - text: "Publications"
        href: publications.qmd
      - text: "About"
        href: about.qmd
        
    tools:
      - icon: twitter
        href: https://twitter.com/ClementGuichet
        text: Twitter
      - icon: github
        href: https://github.com/LPNC-LANG
        text: LPNC-LANG GitHub
      - icon: github
        href: https://github.com/ClementGuichet
        text: Personal GitHub
      
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    code-copy: true
    code-line-numbers: false
    code-overflow: wrap

editor: visual

