project:
  type: website
  output-dir: docs

website:
  title: "Clement Guichet"
  favicon: "images/favicon.ico"
  open-graph: true
  twitter-card: true
  page-navigation: true
  repo-url: https://github.com/ClementGuichet/clementguichet.github.io
  repo-actions: [edit]
  search: 
    type: overlay
  
  page-footer: 
    background: light
    border: false
    center: "Copyright © 2023, Clement Guichet"
    
  navbar: 
    background: light
    logo: "images/favicon.png"
    title: false
    collapse-below: lg
    left: 
      - text: "About"
        file: content/about.qmd
      - text: "Guide"
        file: content/guide/DTI/setup_win.qmd
      - text: "Research"
        file: content/research.qmd

    tools:
      - icon: twitter
        href: https://twitter.com/ClementGuichet
        text: Twitter
      - icon: github
        href: https://github.com/LPNC-LANG
        text: LPNC-LANG GitHub
      - icon: github
        href: https://github.com/ClementGuichet
        text: Personal GitHub
      
      
  sidebar: 
    - id: guide
      alignment: left
      style: docked
      collapse-level: 3
      contents: 
        - section: "Guide"
          file: content/guide/DTI/setup_win.qmd
          contents: 
          - section: "DTI pipeline (SC)"
            contents:
              - content/guide/DTI/setup_win.qmd
              - content/guide/DTI/setup_lin.qmd
              - content/guide/DTI/DTI.qmd
              - content/guide/DTI/parallel.qmd
          - section: "rs-fMRI pipeline (FC)"
            contents: 
              - content/guide/rs-fMRI/spm.qmd
              - content/guide/rs-fMRI/conn.qmd
          - section: "Graph theory"
            contents: 
              - content/guide/GT/graphvar.qmd
      
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    code-copy: true
    code-line-numbers: false
    code-overflow: wrap
    grid: 
      sidebar-width: 350px

editor: visual

