project:
  type: website
  output-dir: docs

website:
  title: "Clément Guichet, CNRS LPNC, UGA"
  
  page-navigation: true
  back-to-top-navigation: true
  
  repo-url: https://github.com/ClementGuichet
  repo-actions: [edit, issue]
  
  page-footer: 
    background: light
    border: false
    center: "Copyright 2023, Clement Guichet"
        
  sidebar:
    style: "docked"
    search: true
    contents:
      - section: "Pipelines"
        contents:
          - rs-fMRI_documentation.qmd
          - DTI_documentation.qmd
      - file: Publications.qmd
      - file: about.qmd
    
    tools:
      - icon: twitter
        href: https://twitter.com/ClementGuichet
      - icon: github
        text: "LPNC-LANG"
        href: https://github.com/LPNC-LANG
      - icon: github
        text: "Personal"
        href: https://github.com/ClementGuichet
            
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

