---
title: "About"
---

I'm 2nd-year PhD Student in Cognitive and Computational Neuroscience at LPNC, CNRS UMR 5105, UGA, Grenoble, France. My [research project](https://lpnc-d9-preprod.univ-grenoble-alpes.fr/recherche/production-scientifique/projets-en-cours/lumintermod) is about modeling how our brain reorganizes across the lifespan to preserve optimal cognitive (language) performances.

[*Summary:*]{.underline}

Cognitive neuroscience is undergoing a paradigm shift. The abundance of multimodal empirical data, coupled with the unprecendented computational capabilities, is helping to redefine the links between the brain and human behavior. The brain is now understood as a vast network of interactions between cerebral regions from which cognitive operations and processes emerge. Specifically, **language functions (L)** are not isolated but constantly interact with **declarative memory (M)** and **executive functions (EF)**. However, the neural mechanisms underlying this **L-M-EF dynamic** remain unclear. This **cognitomic perspective** (structure-function-cognition) is closely linked to the identification of multimodal L-M-EF phenotypes, which will enable significant advances in both fundamental and clinical research (e.g. pre-habilitation & cognitive rehabilitation).

This project has a theoretical dimension, through the enrichment of a neurocognitive L-M-EF model, and a methodological dimension, through the fusion of multimodal data required to evaluate this model (i.e. structural, functional, cognitive-behavioral: cognitomic).
